[build]
  command = "bash ./netlify-build.sh"
  publish = "apps/focus_app/build/web"

[build.environment]
  # Optional: set these in Netlify UI to inject Supabase config at build time
  # SUPABASE_URL = "https://xyzcompany.supabase.co"
  # SUPABASE_ANON_KEY = "your-anon-key"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Let SPA routes fallback to index.html (Flutter web)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
